version: "3.7"
services:
    postgresql:
      image: postgres:12
      environment:
        - POSTGRES_USER=sonar
        - POSTGRES_PASSWORD=secret
        - POSTGRES_DB=sonar
        - PGDATA=/var/lib/postgresql/data/pgdata
      volumes:
        - type: volume
          source: postgres-data
          target: /var/lib/postgresql/data/pgdata
    sonarqube:
      image: sonarqube:8.2-community
      environment:
        - SONAR_JDBC_URL=jdbc:postgresql://postgresql/sonar
        - SONAR_JDBC_USERNAME=sonar
        - SONAR_JDBC_PASSWORD=secret
      volumes:
        - type: bind
          source: ./sonarqube/data
          target: /opt/sonarqube/data
        - type: bind
          source: ./sonarqube/extensions
          target: /opt/sonarqube/extensions
        - type: bind
          source: ./sonarqube/logs
          target: /opt/sonarqube/logs
      ports:
        - "9000:9000"
volumes:
  postgres-data: